### ISSUE TITLE
Setup rJava and Java in Windows

### ISSUE THREAD

**Issue by Lin-Rachmaninoff** [MD-Anderson-Bioinformatics/BatchEffectsPackage#1]
Hi, Professor Casasent.
I am trying to install MBatch in Rstudio. My window system version is Win10 x64，R version 4.0.3, and JAVA 8 is also installed.
I have tried two methods to install MBatch, but all failed. 

**First**, I try _devtools::install_github("MD-Anderson-Bioinformatics/MBatch/package")_. The error message is 
              Error: package or namespace load failed for 'rJava':
              .onLoad failed in loadNamespace() for 'rJava', details:
              call: fun(libname, pkgname)
              error: JAVA_HOME cannot be determined from the Registry
              Error : package 'rJava' could not be loaded

**Then** I turn to this new version of MBatch. After download and uncompress _https://github.com/MD-Anderson-Bioinformatics/BatchEffectsPackage/archive/2020-09-11-1000.zip_, I run _devtools::install("/extract/path/BatchEffectsPackage-2020-09-11-1000/apps/MBatch")_. The error message is as below : 
              "** building package indices
               ** installing vignettes
               ** testing if installed package can be loaded from temporary location
               *** arch - i386
               Error: package or namespace load failed for 'MBatch':
               .onLoad failed in loadNamespace() for 'rJava', details:
               call: fun(libname, pkgname)
               error: JAVA_HOME cannot be determined from the Registry
               error: load failed
               stop running. "

It seems that both failure may relate to the rJava package. But after re-install rJava, the errors above still exist.

**Comment by TDCasasent** [comment]
Have you looked at this document, in particular section 6.1? https://github.com/MD-Anderson-Bioinformatics/BatchEffectsPackage/blob/master/docs/MBatch/MBatch_01_InstallWindows.pdf

From what you've posted, it sounds like an rJava issue. What is the output of the below test from the above document?

```
library(rJava)
.jinit()
J(“java.lang.System”)$getProperty(“java.version”)
```

**Comment by Lin-Rachmaninoff** [comment]
> Have you looked at this document, in particular section 6.1? https://github.com/MD-Anderson-Bioinformatics/BatchEffectsPackage/blob/master/docs/MBatch/MBatch_01_InstallWindows.pdf
> 
> From what you've posted, it sounds like an rJava issue. What is the output of the below test from the above document?
> 
> ```
> library(rJava)
> .jinit()
> J(“java.lang.System”)$getProperty(“java.version”)
> ```

**Comment by Lin-Rachmaninoff** [comment]
Yes, in the beginning, I followed the "MBatch_01_InstallWindows.pdf" to install, but most of the packages were not available for R 4.0.3. So I used the codes on the "8 Dec 2020 version" and successfully install all other packages.
The output of the rJava test is as below: 

> 
> library(rJava)
> .jinit()
[1] 0
> J("java.lang.System")$getProperty("java.version")
[1] "15.0.2"

**Comment by TDCasasent** [comment]
It looks like rJava and Java are not configured properly on your machine -- note how the rJava run above says version 15 for Java. (This is also suggested by the JAVA_HOME error in the earlier posts.)

Did you install Java 8 (64 bit) using the Windows installer as per the document above? This will setup (I believe) all the environmental variables needed.

There should be a control panel to select your active/current Java version. See here:
https://www.java.com/en/download/help/update_runtime_settings.html

You will need to select Java 8 as the version you want to use.

If you get the "JAVA_HOME cannot be determined from the Registry" again, you can look here https://www.r-statistics.com/tag/rjava/ which specifically covers that error. But for now, lets work on getting the correct version registered.

I am working on a new release of MBatch and the associated applications -- current very tentative projection is 4+ weeks off.

**Comment by Lin-Rachmaninoff** [comment]
I re-install Java, R, and Rstudio. RDK was uninstalled as well. Now the software version is Java 8 (64 bit). R 4.0.4 (64 bit), and Rstudio 1.4.1106 (global setting→R version: [64-bit] C:\Program Files\R\R-4.0.4). 
Then I run the rJava test codes, with results as below:
```
> library(rJava)
> .jinit()
> J("java.lang.System")$getProperty("java.version")
[1] "1.8.0_281"
```
And I try to install Mbatch again by running _devtools::install("/extract/path/BatchEffectsPackage-2020-09-11-1000/apps/MBatch")_. But the error still exist as before. 
```
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
*** arch - i386
Error: package or namespace load failed for 'MBatch':
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: fun(libname, pkgname)
  error: No CurrentVersion entry in Software/JavaSoft registry! Try re-installing Java and make sure R and Java have matching architectures.
error: load failed
stop running
*** arch - x64
ERROR: loading failed for 'i386'
* removing 'C:/Users/86138/Documents/R/win-library/4.0/MBatch'
Error in (function (command = NULL, args = character(), error_on_status = TRUE,  : 
  System command 'Rcmd.exe' failed, exit status: 1, stdout & stderr were printed
Type .Last.error.trace to see where the error occured
```
I tried again in the R i386 4.0.4 (32 bit)，and the error message is as below:
```
Running "C:/PROGRA~1/R/R-40~1.4/bin/i386/Rcmd.exe" INSTALL "C:\Users\86138\AppData\Local\Temp\RtmpwD4t3c/MBatch_1.7.1.tar.gz" --install-tests 
* installing to library 'C:/Users/86138/Documents/R/win-library/4.0'
* installing *source* package 'MBatch' ...
** using staged installation
** R
** inst
** tests
** byte-compile and prepare package for lazy loading
error: .onLoad failed in loadNamespace() for 'rJava', details:
  call: fun(libname, pkgname)
  error: No CurrentVersion entry in Software/JavaSoft registry! Try re-installing Java and make sure R and Java have matching architectures.
stop running
ERROR: lazy loading failed for package 'MBatch'
* removing 'C:/Users/86138/Documents/R/win-library/4.0/MBatch'
Error in (function (command = NULL, args = character(), error_on_status = TRUE,  : 
  System command 'Rcmd.exe' failed, exit status: 1, stdout & stderr were printed
Type .Last.error.trace to see where the error occured

```

**Comment by TDCasasent** [comment]
It looks like you still have some sort of Java issue. Notice how both the logs you sent are failing on 32-bit (i386) Java attempts. This shouldn't even be there. I suspect that what is happening is that the install/build commands are trying to build both 32 and 64 bit, since that is what you have installed. rJava can't do that, so it fails. (Which is why the plain-old rJava test works -- it doesn't try to do the 32-bit portion.)

From https://www.oracle.com/java/technologies/javase/javase-jdk8-downloads.html
Get the x86 -- this is the 64-bit only Java, as described in section 3 here https://github.com/MD-Anderson-Bioinformatics/BatchEffectsPackage/blob/master/docs/MBatch/MBatch_01_InstallWindows.pdf
Completely uninstall the old 32-bit/64-bit x86 installation. And try the new one.

**Comment by Lin-Rachmaninoff** [comment]
Haha, finally succeed! 
the x64 version of JDK works. After installing "jdk-8u281-windows-x64.exe (window x64)", users should change the  Environment Variables. Details:

>  Windows → Setting → search for "advanced system settings" →  choose “Advance" and click "Environment Variables"
>  → click “New...”  to create a new system variable → Variable Name: JAVA_HOME → Variable value: installation path of JDK
>  (right pattern of the path like this:  C：\ Program Files \ Java \ jdk1.8.0_60)
> After setting system variables, check the CMD with "java -version", and see "Java HotSpot(TM) 64-Bit Server VM" .


Install MBatch again, no error occurred and finally succeed.
```
> library(MBatch)
All sorting in this package requires using a Sys.setlocale("LC_COLLATE","C"). MBatch Version: 2020-08-31-0800
```

Thanks for Prof. Casasent's kindful help. Thanks♪(･ω･)ﾉ

**Comment by TDCasasent** [comment]
Awesome! Good to hear.
I will close this then.
